# Generated by Django 5.1.5 on 2025-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
